all: iterative recursive random

iterative: iterative.c hw1.c
	gcc -g --std=gnu99 iterative.c hw1.c -o iterative

random: random.c hw1.c
	gcc -g --std=gnu99 random.c hw1.c -o random

recursive: recursive.c hw1.c
	gcc -g --std=gnu99 recursive.c hw1.c -o recursive

clean: 
	rm iterative recursive random
